### ISSUE TITLE
HttpEventlogCollector and sourceType

### ISSUE THREAD

**Issue by albertromkes** [serilog/serilog-sinks-splunk#38]
When posting an entry with the 'sourceType' parameter set, I'll get a 404 bad request back from Splunk (version 6.4.1). If I change 'sourceType' into 'sourcetype' (all lowercase), it starts working.

I'm not sure if this is a setting in Splunk itself or a bug in this sink. If it's a bug, let me know. Then I'll create a pull request with a fix.

**Comment by merbla** [comment]
Hey @albertromkes,

Thanks for the note.  I can confirm the bug, I believe it relates to changes to a new JSON formatter.

It relates to https://github.com/serilog/serilog-sinks-splunk/blob/dev/src/Serilog.Sinks.Splunk/Sinks/Splunk/SplunkJsonFormatter.cs#L80 as you mentioned.

If you are happy to do a PR that would be great, otherwise let me know and I will jump on it.

**Comment by merbla** [comment]
@albertromkes the new package is up at [Nuget](https://www.nuget.org/packages/Serilog.Sinks.Splunk/2.1.1).
